use new regb colors
ImagingDataCommons/Cloud-Resources-Workflows pull request #37
Opened 2023-12-20 02:18 UTC by vkt1414

This PR address #10 

The new colors were chosen such that each distinguishing vertebrae will be easier.
A sample image looks like this.
![new_colors](https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/assets/115020590/8901ad78-3a6f-4f7d-9d68-3e036adfca87)

Here's the link to the CT files and SEG file associated with the example above, with new rgb colors for segmentations.

https://drive.google.com/file/d/1mxyT5TJR6BVGyPdGGmsTKTqKmliL4f5G/view?usp=sharing

2023-12-20 17:55 UTC, fedorov requested changes
This should be revisited as discussed in #39.

2023-12-28 18:57 UTC, fedorov requested changes
After merging the prior PR, there are conflicts in this one

2023-12-28 19:00 UTC, vkt1414 commented
> After merging the prior PR, there are conflicts in this one

I'll resolve the conflicts and rebase

2023-12-29 15:32 UTC, fedorov approved these changes

2023-12-29 15:33 UTC, merged